Repository googleapis/python-crc32c, pull requests merged in 2024-08, with the labels that each got.

#230 build: Bump cibuildwheel to 2.20.0 to build CPython 3.13 wheels
  .github/workflows/presubmit.yml
Labels: size: xs

#236 build: add release scripts using kokoro
  .kokoro/build.sh
  .kokoro/release-manylinux-wheel.sh
  .kokoro/release-osx-wheel.sh
  .kokoro/release-windows-wheel.bat
  .kokoro/release/linux/common.cfg
  .kokoro/release/linux/linux_wheel.cfg
  .kokoro/release/osx/common.cfg
  .kokoro/release/osx/osx-slcn_wheel.cfg
  .kokoro/release/osx/osx_wheel.cfg
  .kokoro/release/windows/common.cfg
  .kokoro/release/windows/windows_wheel.cfg
  owlbot.py
  scripts/manylinux/build.sh
  scripts/manylinux/publish_python_wheel.sh
  scripts/osx/build_python_wheel.sh
  scripts/osx/publish_python_wheel.sh
Labels: size: l

#238 build: remove builds via github actions
  .github/sync-repo-settings.yaml
  .github/workflows/presubmit.yml
Labels: size: m

#237 build: fix windows presubmit
  scripts/windows/build.bat
  setup.py
Labels: size: xs

#242 build: use correct osx wheels for publication
  .kokoro/docker/docs/requirements.txt
  scripts/osx/publish_python_wheel.sh
Labels: size: xs
